### ISSUE TITLE
An error occurred when I used nodeport to connect to kafka in ssl mode

### ISSUE THREAD

**Issue by kubecto** [rafaelmnatali/kafka-k8s#7]
Using a document works fine to get the topic, but I tried to add a nodeport and then tried to get the topic using client
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-external
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: external
    port: 9094
    targetPort: 9092
    nodePort: 30001
  - name: external-ssl
    port: 9095
    targetPort: 9093
    nodePort: 30002
  selector:
    app: kafka

```

```
kafka-topics --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9093 --list --command-config /etc/kafka/secrets/client_security.properties
test-ssl
```

```
[appuser@kafka-cli ~]$ kafka-topics --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9093 --list --command-config /etc/kafka/secrets/client_security.properties
test-ssl
[appuser@kafka-cli ~]$ ls
[appuser@kafka-cli ~]$ cat /etc/kafka/secrets/client_security.properties
security.protocol=SSL
ssl.truststore.location=/etc/kafka/secrets/kafka.client.truststore.jks
ssl.truststore.password=123456
[appuser@kafka-cli ~]$ kafka-topics --bootstrap-server 10.102.28.60:30002 --list --command-config /etc/kafka/secrets/client_security.properties
[2024-06-07 09:56:48,093] ERROR [AdminClient clientId=adminclient-1] Connection to node -1 (/10.102.28.60:30002) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2024-06-07 09:56:48,094] WARN [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error (org.apache.kafka.clients.admin.internals.AdminMetadataManager)
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLHandshakeException: No subject alternative names present
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:360)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:298)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
```
